### ISSUE TITLE
Error: There is no procedure with the name db.constraints registered for this database instance

### ISSUE THREAD

**Issue by xStevex** [zeronetworks/BlueHound#12]
I have this error: "Error: There is no procedure with the name db.constraints registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed."

![image](https://user-images.githubusercontent.com/27353963/217905967-e3a90f34-0b42-4565-aeb0-c283c375e436.png)

As I understand BlueHound is using old procedure "db.constraints" that is removed from neo4j.

How can I fix it?

**Comment by dekelpaz** [comment]
Fixed in version 1.1.1.
