### ISSUE TITLE
BloodHound Upload

### ISSUE THREAD

**Issue by spyr0-sec** [zeronetworks/BlueHound#15]
Using v1.1.1 of BlueHound I seem to be unable to use the BloodHound Upload functionality. 

Using the latest version of SharpHound.exe I get the following error message:

![image](https://github.com/zeronetworks/BlueHound/assets/78267628/6d3e1211-5138-451a-9bc8-6981b165cc28)

v4.3.0 of SharpHound.exe produces the same error however the result is "DROP CONSTRAINT 7" 

This is not an issue on v1.1.0 of BlueHound using either v4.3.0 or v4.3.1 of SharpHound.exe

The offending function may be this?

https://github.com/zeronetworks/BlueHound/blob/master/src/collectors/BloodHoundUploader.tsx#L317

**Comment by dekelpaz** [comment]
What version of neo4j are you using?

**Comment by spyr0-sec** [comment]
Apologies I was running v5 of neo4j. I'll close the issue
