### ISSUE TITLE
Keep getting errors

### ISSUE THREAD

**Issue by Bundybun** [zeronetworks/BlueHound#5]
Hi,

Probally doing something wrong here but.
After cloning, running npm install, i keep getting the same error.
Want to do some testing, so not to experianced with this. Help would be appreciated.
![screenshot1](https://user-images.githubusercontent.com/112402318/187214935-2fc9cb1b-58cc-4257-b8a3-485b07dbc78d.PNG)

**Comment by dekelpaz** [comment]
Did you try running npm install --force?

**Comment by Bundybun** [comment]
Yes. I did try this, will get some errors aswell. After also not able to build

**Comment by dekelpaz** [comment]
Can you please share the log you got when running with --force?

**Comment by Bundybun** [comment]
![screenshot2](https://user-images.githubusercontent.com/112402318/187916673-6eb160b0-e15a-481a-8f1a-82591cbe1d20.PNG)
![screenshot3](https://user-images.githubusercontent.com/112402318/187916679-d45dede7-65a4-4f8a-a028-f4249d8bff0d.PNG)

**Comment by dekelpaz** [comment]
OK now try running it with:
`npx webpack-dev-server --mode development`

**Comment by Bundybun** [comment]
Works! Thanks for the awesome help my friend!

**Comment by dekelpaz** [comment]
Glad to hear :)
