### ISSUE TITLE
Available only in Electron error

### ISSUE THREAD

**Issue by 3isenHeiM** [zeronetworks/BlueHound#6]
Hi,

I've installed BlueHound on a Debian VM, and everything went fine.

However, I have trouble specifying the path to the tools in the WebUI.

I get an "Available only in Electron" error :

![image](https://user-images.githubusercontent.com/26417172/188475626-b871014b-1581-45b7-b8bc-5e4da6bdfa35.png)

Any ideas where I messed up ?

**Comment by dekelpaz** [comment]
These features can only work when running BlueHound from Electron. 
You can either download a pre-compiled binary from the release page or compile it yourself from the source code.
