### ISSUE TITLE
Not working on KALI LINUX

### ISSUE THREAD

**Issue by shariqmalik** [zeronetworks/BlueHound#7]
### BlueHound is not working on KALI LINUX
I'm using the latest binary from the [releases](https://github.com/zeronetworks/BlueHound/releases/).
Whenever I run the binary. Although there is no error, but the tool is not working.

**Screenshot:**
![image](https://user-images.githubusercontent.com/19536819/197781640-3c324f00-8544-4c4e-85a1-19bd0c827df9.png)

**Comment by dekelpaz** [comment]
Try running with:
 ./bluehound --no-sandbox

**Comment by shariqmalik** [comment]
Still not working 🥺 
![image](https://user-images.githubusercontent.com/19536819/198755759-5dde0208-af2a-462d-bd7f-fb54dae9a477.png)

**Comment by mtimani** [comment]
Same issue for me :(

strace command shows the following errors :
![BlueHound](https://user-images.githubusercontent.com/34349792/199002469-005c902f-2506-4250-87c1-4a38d467544b.png)

Indeed the ./resources/ directory is empty.

**Comment by mtimani** [comment]
Same issue for me

**Comment by mtimani** [comment]
Found a fix:
Download the 1.0.0 release and copy ./resource/app direcory to the 1.1.0 version unzipped resource folder.

Crappy fix, but works.
I think the app directory was just forgotten in the latest release...

**Comment by dekelpaz** [comment]
Updated the linux zip file in the [release page](https://github.com/zeronetworks/BlueHound/releases/tag/v1.1.0). 
Can you please check if this fixes the issue for you?

**Comment by shariqmalik** [comment]
Thanks @mtimani  and @dekelpaz 
Its working now,
