### ISSUE TITLE
Arguments with Double Dashes (--) not parsed correctly on at least 1 data import tool  

### ISSUE THREAD

**Issue by theSha1chemist** [zeronetworks/BlueHound#8]
Hi and thanks for this tool! 

I'm having trouble using arguments with double dashes on the SharpHound data import. 

Example of sharphound working as expected with single dash argument `-c`:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3621264/200371647-48084034-7e1f-4c37-b677-8a4fcd25fca9.png">

Attempting execute the same command with a double dash argument `--CollectionMethod`:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/3621264/200372866-062888b0-1e77-4d62-99d8-5aff7fe2f17a.png">

This is preventing me from using arguments that don't have single dashes associated with them, like `--LdapUsername` or `--LdapPassword` and therefore i'm not able to use the tool currently

**Comment by dekelpaz** [comment]
Could you try splitting to different arguments? For example:
![image](https://user-images.githubusercontent.com/95357879/200849370-3d43b748-67ed-49cb-92c3-3364042da87e.png)
