### ISSUE TITLE
[Feature Request] Export dashboard without data

### ISSUE THREAD

**Issue by arvchristos** [zeronetworks/BlueHound#9]
Hello,

Thank you for the pretty useful tool! We are considering using it in the organization I work for. During evaluating it, we realized that it would be useful to be able to export the dashboards definition without data. This would enable us to version control the definition without publishing actual query results.

**Comment by dekelpaz** [comment]
Hi,

This is already possible, just go to "Save Dashboard" section (save icon on the left toolbar) and you will be able to export a JSON file of the dashboard definition.
This JSON can also be loaded using the "Load Dashboard" section.

**Comment by arvchristos** [comment]
Hello @dekelpaz 

Thank you for responding. I am already aware that there is export functionality built for Bluehound. However, if you try to export after running queries, what you get is a snapshot of Bluehound dashboards, meaning the *setup/layout* along with *data*. My feature request was to also add the functionality to save only the dashboard setup/layouts without the query data.

**Comment by arvchristos** [comment]
I stand corrected @dekelpaz , It seems that only the dashboard definition is exported. What I thought as data is the `nodePositions`
